# Generated by Django 5.2.15 on 2026-06-30 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConteudoInstitucional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secao', models.CharField(choices=[('SOBRE', 'Sobre'), ('MISSAO', 'Missão'), ('VISAO', 'Visão'), ('VALORES', 'Valores')], max_length=10, verbose_name='seção')),
                ('titulo', models.CharField(max_length=200, verbose_name='título')),
                ('texto', models.TextField(verbose_name='texto')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='institucional/', verbose_name='imagem')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('is_ativo', models.BooleanField(default=True, verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'conteúdo institucional',
                'verbose_name_plural': 'conteúdos institucionais',
                'ordering': ['secao', 'ordem'],
            },
        ),
        migrations.CreateModel(
            name='Depoimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_aluno', models.CharField(max_length=150, verbose_name='nome do aluno')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='depoimentos/', verbose_name='foto')),
                ('nome_curso', models.CharField(blank=True, max_length=150, verbose_name='nome do curso')),
                ('texto', models.TextField(verbose_name='depoimento')),
                ('is_publicado', models.BooleanField(default=False, verbose_name='publicado')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='ordem de exibição')),
            ],
            options={
                'verbose_name': 'depoimento',
                'verbose_name_plural': 'depoimentos',
                'ordering': ['ordem', 'nome_aluno'],
            },
        ),
        migrations.CreateModel(
            name='MembroEquipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='nome')),
                ('cargo', models.CharField(max_length=120, verbose_name='cargo')),
                ('bio', models.TextField(blank=True, verbose_name='bio')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='equipe/', verbose_name='foto')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('is_ativo', models.BooleanField(default=True, verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'membro da equipe',
                'verbose_name_plural': 'membros da equipe',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='título')),
                ('conteudo', models.TextField(verbose_name='conteúdo')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='posts/', verbose_name='imagem')),
                ('categoria', models.CharField(blank=True, max_length=80, verbose_name='categoria')),
                ('data_publicacao', models.DateTimeField(verbose_name='data de publicação')),
                ('is_publicado', models.BooleanField(default=False, verbose_name='publicado')),
            ],
            options={
                'verbose_name': 'post',
                'verbose_name_plural': 'posts',
                'ordering': ['-data_publicacao'],
            },
        ),
    ]
