# Generated by Django 5.2.15 on 2026-07-01 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, unique=True, verbose_name='slug'),
        ),
    ]
