# Generated by Django 5.2.15 on 2026-07-01 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conteudoinstitucional',
            name='secao',
            field=models.CharField(choices=[('HERO', 'Hero (banner inicial)'), ('SOBRE', 'Sobre'), ('MISSAO', 'Missão'), ('VISAO', 'Visão'), ('VALORES', 'Valores')], max_length=10, verbose_name='seção'),
        ),
    ]
