# Generated by Django 5.2.15 on 2026-06-30 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='nome')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='cursos/', verbose_name='imagem')),
                ('tipo', models.CharField(choices=[('GRADUACAO', 'Graduação'), ('FORMACAO', 'Formação')], max_length=20, verbose_name='tipo')),
                ('carga_horaria', models.PositiveIntegerField(default=0, verbose_name='carga horária (horas)')),
                ('preco_base', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='preço base')),
            ],
            options={
                'verbose_name': 'curso',
                'verbose_name_plural': 'cursos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='nome')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('ementa', models.TextField(blank=True, verbose_name='ementa')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinas', to='cursos.curso', verbose_name='curso')),
            ],
            options={
                'verbose_name': 'disciplina',
                'verbose_name_plural': 'disciplinas',
                'ordering': ['curso', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='nome')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('ordem', models.PositiveIntegerField(default=1, verbose_name='ordem')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulos', to='cursos.curso', verbose_name='curso')),
            ],
            options={
                'verbose_name': 'módulo',
                'verbose_name_plural': 'módulos',
                'ordering': ['curso', 'ordem'],
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=120, verbose_name='nome/identificação')),
                ('vagas_totais', models.PositiveIntegerField(default=0, verbose_name='vagas totais')),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('FECHADA', 'Fechada'), ('ENCERRADA', 'Encerrada')], default='ABERTA', max_length=20, verbose_name='status')),
                ('prazo_matricula_pos_vestibular', models.DateField(blank=True, null=True, verbose_name='prazo de matrícula pós-vestibular')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turmas', to='cursos.curso', verbose_name='curso')),
            ],
            options={
                'verbose_name': 'turma',
                'verbose_name_plural': 'turmas',
                'ordering': ['curso', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='ProgressoModuloTurma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('ATIVO', 'Ativo'), ('CONCLUIDO', 'Concluído')], default='PENDENTE', max_length=20, verbose_name='status')),
                ('is_ativo', models.BooleanField(default=False, verbose_name='ativo')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressos', to='cursos.modulo', verbose_name='módulo')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressos_modulo', to='cursos.turma', verbose_name='turma')),
            ],
            options={
                'verbose_name': 'progresso de módulo na turma',
                'verbose_name_plural': 'progressos de módulos nas turmas',
                'ordering': ['turma', 'modulo'],
            },
        ),
        migrations.CreateModel(
            name='HorarioFormacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_1', models.CharField(choices=[('SEG', 'Segunda-feira'), ('TER', 'Terça-feira'), ('QUA', 'Quarta-feira'), ('QUI', 'Quinta-feira'), ('SEX', 'Sexta-feira'), ('SAB', 'Sábado')], max_length=3, verbose_name='primeiro dia')),
                ('dia_2', models.CharField(choices=[('SEG', 'Segunda-feira'), ('TER', 'Terça-feira'), ('QUA', 'Quarta-feira'), ('QUI', 'Quinta-feira'), ('SEX', 'Sexta-feira'), ('SAB', 'Sábado')], max_length=3, verbose_name='segundo dia')),
                ('horario_inicio', models.TimeField(verbose_name='horário de início')),
                ('duracao_minutos', models.PositiveSmallIntegerField(default=60, verbose_name='duração do slot (min)')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_formacao', to='cursos.turma', verbose_name='turma')),
            ],
            options={
                'verbose_name': 'horário de formação',
                'verbose_name_plural': 'horários de formação',
            },
        ),
        migrations.CreateModel(
            name='Ciclo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(verbose_name='número do ciclo')),
                ('data_inicio', models.DateField(verbose_name='data de início')),
                ('data_fim', models.DateField(verbose_name='data de fim')),
                ('is_ativo', models.BooleanField(default=False, verbose_name='ativo')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciclos', to='cursos.turma', verbose_name='turma')),
            ],
            options={
                'verbose_name': 'ciclo',
                'verbose_name_plural': 'ciclos',
                'ordering': ['turma', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='AtribuicaoProfessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atribuicoes', to='accounts.professor', verbose_name='professor')),
                ('disciplina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='atribuicoes', to='cursos.disciplina', verbose_name='disciplina')),
                ('modulo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='atribuicoes', to='cursos.modulo', verbose_name='módulo')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atribuicoes', to='cursos.turma', verbose_name='turma')),
            ],
            options={
                'verbose_name': 'atribuição de professor',
                'verbose_name_plural': 'atribuições de professores',
            },
        ),
        migrations.CreateModel(
            name='GradeHoraria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(choices=[('SEG', 'Segunda-feira'), ('QUA', 'Quarta-feira'), ('SAB', 'Sábado')], max_length=3, verbose_name='dia da semana')),
                ('horario', models.TimeField(verbose_name='horário de início')),
                ('slots', models.PositiveSmallIntegerField(default=1, verbose_name='slots de aula')),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='cursos.ciclo', verbose_name='ciclo')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='cursos.disciplina', verbose_name='disciplina')),
            ],
            options={
                'verbose_name': 'grade horária',
                'verbose_name_plural': 'grades horárias',
                'ordering': ['ciclo', 'dia_semana', 'horario'],
                'constraints': [models.UniqueConstraint(fields=('ciclo', 'disciplina', 'dia_semana'), name='grade_unica_por_ciclo_disciplina_dia')],
            },
        ),
        migrations.AddConstraint(
            model_name='modulo',
            constraint=models.UniqueConstraint(fields=('curso', 'ordem'), name='modulo_ordem_unica_por_curso'),
        ),
        migrations.AddConstraint(
            model_name='progressomoduloturma',
            constraint=models.UniqueConstraint(fields=('turma', 'modulo'), name='progresso_unico_por_turma_modulo'),
        ),
        migrations.AddConstraint(
            model_name='progressomoduloturma',
            constraint=models.UniqueConstraint(condition=models.Q(('is_ativo', True)), fields=('turma',), name='progresso_unico_ativo_por_turma'),
        ),
        migrations.AddConstraint(
            model_name='ciclo',
            constraint=models.UniqueConstraint(fields=('turma', 'numero'), name='ciclo_numero_unico_por_turma'),
        ),
        migrations.AddConstraint(
            model_name='ciclo',
            constraint=models.UniqueConstraint(condition=models.Q(('is_ativo', True)), fields=('turma',), name='ciclo_unico_ativo_por_turma'),
        ),
        migrations.AddConstraint(
            model_name='atribuicaoprofessor',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('disciplina__isnull', False), ('modulo__isnull', True)), models.Q(('disciplina__isnull', True), ('modulo__isnull', False)), _connector='OR'), name='atribuicao_disciplina_xor_modulo'),
        ),
    ]
