# Generated by Django 5.2.15 on 2026-06-30 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='data')),
                ('horario_inicio', models.TimeField(verbose_name='horário de início')),
                ('duracao_minutos', models.PositiveSmallIntegerField(default=60, verbose_name='duração (min)')),
                ('cancelada', models.BooleanField(default=False, verbose_name='cancelada')),
                ('motivo_cancelamento', models.TextField(blank=True, null=True, verbose_name='motivo do cancelamento')),
            ],
            options={
                'verbose_name': 'aula',
                'verbose_name_plural': 'aulas',
                'ordering': ['-data', 'horario_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='título')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('data', models.DateField(verbose_name='data')),
                ('nota_maxima', models.DecimalField(decimal_places=2, default=10, max_digits=5, verbose_name='nota máxima')),
            ],
            options={
                'verbose_name': 'avaliação',
                'verbose_name_plural': 'avaliações',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='EntregaTrabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='trabalhos/entregas/', verbose_name='arquivo enviado')),
                ('data_hora_entrega', models.DateTimeField(auto_now_add=True, verbose_name='entregue em')),
                ('nota', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='nota')),
                ('feedback', models.TextField(blank=True, null=True, verbose_name='feedback')),
            ],
            options={
                'verbose_name': 'entrega de trabalho',
                'verbose_name_plural': 'entregas de trabalho',
            },
        ),
        migrations.CreateModel(
            name='Frequencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presente', models.BooleanField(default=False, verbose_name='presente')),
            ],
            options={
                'verbose_name': 'frequência',
                'verbose_name_plural': 'frequências',
            },
        ),
        migrations.CreateModel(
            name='ResultadoAvaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='nota')),
            ],
            options={
                'verbose_name': 'resultado de avaliação',
                'verbose_name_plural': 'resultados de avaliação',
            },
        ),
        migrations.CreateModel(
            name='Trabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='título')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('prazo_entrega', models.DateTimeField(verbose_name='prazo de entrega')),
                ('arquivo_enunciado', models.FileField(blank=True, null=True, upload_to='trabalhos/enunciados/', verbose_name='arquivo de enunciado')),
            ],
            options={
                'verbose_name': 'trabalho',
                'verbose_name_plural': 'trabalhos',
                'ordering': ['-prazo_entrega'],
            },
        ),
    ]
