# Generated by Django 5.2.15 on 2026-06-30 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0001_initial'),
        ('accounts', '0001_initial'),
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='ciclo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aulas', to='cursos.ciclo', verbose_name='ciclo'),
        ),
        migrations.AddField(
            model_name='aula',
            name='disciplina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='cursos.disciplina', verbose_name='disciplina'),
        ),
        migrations.AddField(
            model_name='aula',
            name='modulo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='cursos.modulo', verbose_name='módulo'),
        ),
        migrations.AddField(
            model_name='aula',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='cursos.turma', verbose_name='turma'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='disciplina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='cursos.disciplina', verbose_name='disciplina'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='modulo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='cursos.modulo', verbose_name='módulo'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='cursos.turma', verbose_name='turma'),
        ),
        migrations.AddField(
            model_name='entregatrabalho',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas_trabalho', to='accounts.aluno', verbose_name='aluno'),
        ),
        migrations.AddField(
            model_name='frequencia',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frequencias', to='accounts.aluno', verbose_name='aluno'),
        ),
        migrations.AddField(
            model_name='frequencia',
            name='aula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frequencias', to='academico.aula', verbose_name='aula'),
        ),
        migrations.AddField(
            model_name='frequencia',
            name='lancado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='frequencias_lancadas', to='accounts.professor', verbose_name='lançada por'),
        ),
        migrations.AddField(
            model_name='resultadoavaliacao',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados_avaliacao', to='accounts.aluno', verbose_name='aluno'),
        ),
        migrations.AddField(
            model_name='resultadoavaliacao',
            name='avaliacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='academico.avaliacao', verbose_name='avaliação'),
        ),
        migrations.AddField(
            model_name='resultadoavaliacao',
            name='lancado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultados_lancados', to='accounts.professor', verbose_name='lançada por'),
        ),
        migrations.AddField(
            model_name='trabalho',
            name='disciplina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='cursos.disciplina', verbose_name='disciplina'),
        ),
        migrations.AddField(
            model_name='trabalho',
            name='modulo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='cursos.modulo', verbose_name='módulo'),
        ),
        migrations.AddField(
            model_name='trabalho',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='cursos.turma', verbose_name='turma'),
        ),
        migrations.AddField(
            model_name='entregatrabalho',
            name='trabalho',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='academico.trabalho', verbose_name='trabalho'),
        ),
        migrations.AddConstraint(
            model_name='frequencia',
            constraint=models.UniqueConstraint(fields=('aula', 'aluno'), name='frequencia_unica_aula_aluno'),
        ),
        migrations.AddConstraint(
            model_name='resultadoavaliacao',
            constraint=models.UniqueConstraint(fields=('avaliacao', 'aluno'), name='resultado_unico_avaliacao_aluno'),
        ),
        migrations.AddConstraint(
            model_name='entregatrabalho',
            constraint=models.UniqueConstraint(fields=('trabalho', 'aluno'), name='entrega_unica_trabalho_aluno'),
        ),
    ]
