# Generated by Django 5.2.15 on 2026-07-01 01:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregatrabalho',
            name='entregue_em_atraso',
            field=models.BooleanField(default=False, verbose_name='entregue em atraso'),
        ),
        migrations.AlterField(
            model_name='entregatrabalho',
            name='data_hora_entrega',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='entregue em'),
        ),
    ]
