# Generated by Django 5.2.15 on 2026-06-30 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EdicaoVestibular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_prova', models.DateField(verbose_name='data da prova')),
                ('local_prova', models.CharField(max_length=255, verbose_name='local da prova')),
                ('prazo_matricula', models.DateField(verbose_name='prazo de matrícula após aprovação')),
                ('resultado_pdf', models.FileField(blank=True, null=True, upload_to='vestibular/resultados/', verbose_name='PDF de resultado')),
                ('resultado_publicado', models.BooleanField(default=False, verbose_name='resultado publicado')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edicoes_vestibular', to='cursos.turma', verbose_name='turma')),
            ],
            options={
                'verbose_name': 'edição de vestibular',
                'verbose_name_plural': 'edições de vestibular',
                'ordering': ['-data_prova'],
            },
        ),
        migrations.CreateModel(
            name='CandidatoVestibular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='nome')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='telefone')),
                ('status', models.CharField(choices=[('INSCRITO', 'Inscrito'), ('APROVADO', 'Aprovado'), ('REPROVADO', 'Reprovado'), ('LISTA_ESPERA', 'Lista de espera'), ('DESISTIU', 'Desistiu')], default='INSCRITO', max_length=15, verbose_name='status')),
                ('notificado_por_email', models.BooleanField(default=False, verbose_name='notificado por email')),
                ('edicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatos', to='vestibular.edicaovestibular', verbose_name='edição')),
            ],
            options={
                'verbose_name': 'candidato de vestibular',
                'verbose_name_plural': 'candidatos de vestibular',
                'ordering': ['nome'],
                'constraints': [models.UniqueConstraint(fields=('edicao', 'cpf'), name='candidato_unico_por_edicao_cpf')],
            },
        ),
    ]
