# Generated by Django 5.2.15 on 2026-06-30 20:16

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cupom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=40, unique=True, verbose_name='código')),
                ('tipo_desconto', models.CharField(choices=[('PERCENTUAL', 'Percentual (%)'), ('FIXO', 'Valor fixo (R$)')], max_length=12, verbose_name='tipo de desconto')),
                ('valor_desconto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor do desconto')),
                ('data_inicio', models.DateField(verbose_name='início da validade')),
                ('data_fim', models.DateField(verbose_name='fim da validade')),
                ('max_usos', models.PositiveIntegerField(default=1, verbose_name='máximo de usos')),
                ('usos_atuais', models.PositiveIntegerField(default=0, verbose_name='usos atuais')),
                ('is_ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cupons', to='cursos.curso', verbose_name='curso (opcional)')),
            ],
            options={
                'verbose_name': 'cupom',
                'verbose_name_plural': 'cupons',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('AGUARDANDO_PAGAMENTO', 'Aguardando pagamento'), ('AGUARDANDO_VALIDACAO', 'Aguardando validação'), ('APROVADA', 'Aprovada'), ('REJEITADA', 'Rejeitada')], default='AGUARDANDO_PAGAMENTO', max_length=24, verbose_name='status')),
                ('metodo_pagamento', models.CharField(blank=True, choices=[('PIX', 'PIX'), ('BOLETO', 'Boleto'), ('CARTAO', 'Cartão')], max_length=10, verbose_name='método de pagamento')),
                ('valor_original', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor original')),
                ('desconto_cupom', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='desconto por cupom')),
                ('desconto_promocao', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='desconto por promoção')),
                ('valor_final', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor final')),
                ('asaas_payment_id', models.CharField(blank=True, max_length=120, verbose_name='ID do pagamento (Asaas)')),
                ('url_pagamento', models.URLField(blank=True, verbose_name='URL do pagamento (boleto/QR PIX)')),
                ('motivo_rejeicao', models.TextField(blank=True, verbose_name='motivo da rejeição')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='accounts.aluno', verbose_name='aluno')),
                ('cupom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matriculas', to='matriculas.cupom', verbose_name='cupom aplicado')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='cursos.turma', verbose_name='turma')),
            ],
            options={
                'verbose_name': 'matrícula',
                'verbose_name_plural': 'matrículas',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('RG', 'RG'), ('CPF', 'CPF'), ('HISTORICO_EM', 'Histórico do Ensino Médio')], max_length=15, verbose_name='tipo')),
                ('arquivo', models.FileField(upload_to='documentos/', verbose_name='arquivo')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado')], default='PENDENTE', max_length=10, verbose_name='status')),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='matriculas.matricula', verbose_name='matrícula')),
            ],
            options={
                'verbose_name': 'documento',
                'verbose_name_plural': 'documentos',
            },
        ),
        migrations.CreateModel(
            name='Promocao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_desconto', models.CharField(choices=[('PERCENTUAL', 'Percentual (%)'), ('FIXO', 'Valor fixo (R$)')], max_length=12, verbose_name='tipo de desconto')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor do desconto')),
                ('data_inicio', models.DateField(verbose_name='início')),
                ('data_fim', models.DateField(verbose_name='fim')),
                ('is_ativa', models.BooleanField(default=True, verbose_name='ativa')),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promocoes', to='cursos.curso', verbose_name='curso')),
                ('turma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promocoes', to='cursos.turma', verbose_name='turma')),
            ],
            options={
                'verbose_name': 'promoção',
                'verbose_name_plural': 'promoções',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.AddField(
            model_name='matricula',
            name='promocao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matriculas', to='matriculas.promocao', verbose_name='promoção aplicada'),
        ),
        migrations.AddConstraint(
            model_name='matricula',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'APROVADA')), fields=('aluno', 'turma'), name='matricula_aprovada_unica_por_aluno_turma'),
        ),
    ]
