# Generated by Django 5.2.15 on 2026-06-30 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('cursos', '0001_initial'),
        ('matriculas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='candidato_cpf',
            field=models.CharField(default='', max_length=14, verbose_name='CPF do candidato'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matricula',
            name='candidato_data_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='data de nascimento do candidato'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='candidato_email',
            field=models.EmailField(default='', max_length=254, verbose_name='email do candidato'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matricula',
            name='candidato_nome',
            field=models.CharField(default='', max_length=150, verbose_name='nome do candidato'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matricula',
            name='candidato_telefone',
            field=models.CharField(blank=True, max_length=20, verbose_name='telefone do candidato'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='upload_token',
            field=models.CharField(db_index=True, default='', editable=False, max_length=64, unique=True, verbose_name='token de upload'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='matricula',
            name='aluno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='accounts.aluno', verbose_name='aluno'),
        ),
        migrations.AddConstraint(
            model_name='matricula',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'APROVADA')), fields=('candidato_cpf', 'turma'), name='matricula_aprovada_unica_por_cpf_turma'),
        ),
    ]
