# Generated by Django 5.2.15 on 2026-07-06 18:50

import matriculas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0002_matricula_candidato_cpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='arquivo',
            field=models.FileField(storage=matriculas.models.documento_storage, upload_to='documentos/', verbose_name='arquivo'),
        ),
    ]
